---
- name: Enable SSL on Oracle WebLogic Server
  hosts: all
  gather_facts: false
  tasks:

    - name: Copy Script file
      win_shell: git clone https://github.com/sakirm-icpl/oracle-weblogic.git
      args:
        chdir: C:\
        executable: cmd
        elevate: yes
    
    - name: Copy a single file where the source is on the remote host
      ansible.windows.win_copy:
        src: C:\oracle-weblogic\Enable_SSL_WL.py
        dest: C:\Oracle\Middleware\Oracle_Home\user_projects\domains\base_domain\bin\Enable_SSL_WL.py
        remote_src: true

    - name: run script
      win_shell: |
        C:\Oracle\Middleware\Oracle_Home\user_projects\domains\base_domain\bin\setDomainEnv.cmd
        java weblogic.WLST C:\Oracle\Middleware\Oracle_Home\user_projects\domains\base_domain\bin\Enable_SSL_WL.py
      args:
        executable: powershell.exe
        elevate: yes

    - name: Removing script file
      ansible.windows.win_file:
        path: C:\oracle-weblogic
        state: absent
