- name: Enable SSL on Oracle WebLogic Server
  hosts: all
  gather_facts: false
  tasks:

    - name: Clone repository
      git:
        repo: https://github.com/sakirm-icpl/oracle-weblogic.git
        dest: /root/tmp/oracle-weblogic
      become: yes
    
    - name: Copy certificate.py to domain bin directory
      copy:
        src: /root/tmp/oracle-weblogic/weblogic.py
        dest: /root/script/weblogic.py
        mode: '0755'
        remote_src: true
      become: yes

    - name: Run script
      command:
        cmd: /home/pavan/fmw/domains/poc_domain/bin/setDomainEnv.sh && wlst /root/script/weblogic.py
      become: yes

    - name: Remove cloned repository
      file:
        path: /root/tmp/oracle-weblogic
        state: absent
      become: yes
      run_once: true
