---
- name: Enable SSL on Oracle WebLogic Server
  hosts: all
  gather_facts: false
  become: yes
  tasks:

    - name: Copy Script file
      shell: git clone https://github.com/sakirm-icpl/oracle-weblogic.git
      args:
        chdir: /home/temp
    
    - name: Copy a single file where the source is on the remote host
      copy:
        src: /home/temp/oracle-weblogic/certificate.py
        dest: /home/pavan/fmw/domains/poc_domain/bin/certificate.py
        remote_src: true

    - name: run script
      shell: |
        /home/pavan/fmw/domains/poc_domain/bin/setDomainEnv.sh
        java weblogic.WLST /home/pavan/fmw/domains/poc_domain/bin/certificate.py

    - name: Removing script file
      file:
        path: /home/temp/oracle-weblogic
        state: absent
