- name: Enable SSL on Oracle WebLogic Server
  hosts: all
  gather_facts: false
  tasks:

    - name: Add Script File
      git:
        repo: "https://github.com/sakirm-icpl/oracle-weblogic.git"
        dest: "/root/tmp/oracle-weblogic"
      become: yes
    
    - name: Copy Script.py to Server
      copy:
        src: "/root/tmp/oracle-weblogic/weblogic.py"
        dest: "/home/pavan/script/weblogic.py"
        mode: '0755'
        remote_src: true
      become: yes

    - name: Run WLST script
      command: sudo /home/pavan/fmw/wlserver/common/bin/wlst.sh /home/pavan/script/weblogic.py

    - name: Remove Script File
      file:
        path: "/root/tmp/oracle-weblogic"
        state: absent
      become: yes
      run_once: true
