connect('weblogic','PocWLS0723$','0.0.0.0:7001')
edit()
startEdit()
cd('/Servers/MS1')
cmo.setCustomIdentityKeyStoreFileName('/home/sakir/certificate/Identity.jks')
cmo.setCustomIdentityKeyStoreType('jks')
setEncrypted('CustomIdentityKeyStorePassPhrase', 'CustomIdentityKeyStorePassPhrase_1690451358231', '/home/pavan/fmw/domains/poc_domain/Script1690451302889Config', '/home/pavan/fmw/domains/poc_domain/Script1690451302889Secret')
cmo.setCustomTrustKeyStoreFileName('/home/sakir/certificate/Trust.jks')
cmo.setCustomTrustKeyStoreType('jks')
setEncrypted('CustomTrustKeyStorePassPhrase', 'CustomTrustKeyStorePassPhrase_1690451358275', '/home/pavan/fmw/domains/poc_domain/Script1690451302889Config', '/home/pavan/fmw/domains/poc_domain/Script1690451302889Secret')
save()
activate()
edit()
startEdit()
cd('/Servers/MS1/SSL/MS1')
cmo.setServerPrivateKeyAlias('new')
setEncrypted('ServerPrivateKeyPassPhrase', 'ServerPrivateKeyPassPhrase_1690451382458', '/home/pavan/fmw/domains/poc_domain/Script1690451302889Config', '/home/pavan/fmw/domains/poc_domain/Script1690451302889Secret')
save()
activate()
edit()
startEdit()
cmo.setHostnameVerificationIgnored(true)
cmo.setHostnameVerifier(None)
cmo.setTwoWaySSLEnabled(false)
cmo.setClientCertificateEnforced(false)
save()
activate()
edit()
startEdit()
cmo.setEnabled(true)
save()
activate()
disconnect()
exit()
