- name: Enable SSL on Oracle WebLogic Server
  hosts: all
  gather_facts: false
  tasks:

    - name: Clone repository
      git:
        repo: "https://github.com/sakirm-icpl/oracle-weblogic.git"
        dest: "/root/tmp/oracle-weblogic"
      become: yes
    
    - name: Copy certificate.py to domain bin directory
      copy:
        src: "/root/tmp/oracle-weblogic/weblogic.py"
        dest: "/home/pavan/script/weblogic.py"
        mode: '0755'
        remote_src: true
      become: yes

    - name: Set environment variables
      ansible.builtin.set_fact:
        domain_home: "/home/pavan/fmw/domains/poc_domain"
        script_path: "/home/pavan/script/weblogic.py"

    - name: Run WLST script
      command: "{{ domain_home }}/bin/wlst.sh {{ script_path }}"

    - name: Remove cloned repository
      file:
        path: "/root/tmp/oracle-weblogic"
        state: absent
      become: yes
      run_once: true
